### ISSUE TITLE
Use production Vue CDN

### ISSUE THREAD

**Issue by loneil** [bcgov/lcrb-dav#34]
Recommend adopting change from VCAuthN here:
https://github.com/bcgov/vc-authn-oidc/pull/534

Details in above PR. This would
- Load a much smaller import
- Pin to a stable version taking away production risk when a new Vue version comes out
- Remove console warnings

**Comment by loneil** [comment]
Added change here https://github.com/bcgov/lcrb-dav/pull/35

**Comment by esune** [comment]
Resolved by #35
